### ISSUE TITLE
support SMS

### ISSUE THREAD

**Issue by algethamy** [Laragear/TwoFactor#15]
### Please check these requirements

- [X] This feature helps everyone using this package
- [ ] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

can you support SMS.

### Code sample

```php
no code
```

### Are you a Patreon supporter?

No, don't give priority to this

**Comment by DarkGhostHunter** [comment]
```php
$user->notify(
    new Sms2FANotification($user->makeTwoFactorCode())
);
```
