### ISSUE TITLE
Login fails for users using totp when package is used with sanctum

### ISSUE THREAD

**Issue by OysteinHoiby** [Laragear/TwoFactor#16]
### PHP & Platform

8.0.12

### Laravel verion

9.17.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

When totp code is correct i expect the user to be logged in.

### Description

Users not using 2fa gets logged inn correctly. Users who has activated 2fa are getting the login page again with no error message.

### Reproduction

```php
//To activate sanctum for api calls (SPA authentication) i  uncommented EnsureFrontendRequestsAreStateful in app/http/Kernel.php. That is when this "bug" sets in.

'api' => [
            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
```

### Stack trace & logs

```shell
no stacktrace and nothing logged in laravel.log
```

### Are you a Patreon supporter?

No, don't give priority to this

**Comment by DarkGhostHunter** [comment]
Please, give more details about your authentication flow..

**Comment by DarkGhostHunter** [comment]
I figured out why it doesn't work. [Ensure you're modifying the Authentication Flow to use `Auth2FA`](https://github.com/Laragear/TwoFactor#logging-in).
