### ISSUE TITLE
2fa.confirm middleware do not attach to POST login route.

### ISSUE THREAD

**Issue by denydias** [Laragear/TwoFactor#2]
## Checklist
- [X] I have checked my stack trace and logs.
- [X] I can reproduce this in isolation.
- [ ] I can suggest a workaround or PR.

## Dependencies
- PHP: 8.1.3 Linux
- Laravel: 9.1.0

## Description
**This is NOT a bug report at the moment.**

I just upgraded the project I'm working on to L9. As such I had to move from `darkghosthunter/laraguard` to `laragear/two-factor`. This change required a lot of code change and now I'm not so sure if I took the best path.

My app has no frontend. It's just a backend where all the action happens. All users must be logged in, but not everyone may have 2FA enabled. The `2fa_code` is asked on a dedicated form just after the login one IF the user has 2FA enabled.

So I thought to do this in `routes/web.php`:

```php
Route::post('/', 'Auth\LoginController@login')
    ->name('login.submit')
    ->middleware('2fa.confirm');
```

But nope... it won't work that way. At least it didn't here. Users with 2FA enabled are just logged in as soon as they submit their login credentials. No 2FA form page presented as it used to be in  `darkghosthunter/laraguard` wonderful magic listeners.

After thoroughly reading this package README and many attempts later, the only way I found to accomplish the old behavior was to override L9's `Auth\LoginController@login`. I'm not so confident if I got right and what kind of security holes I may have opened. Here's how it looks now:

```php
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Providers\RouteServiceProvider;
use Auth;
use DB;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Laragear\TwoFactor\TwoFactor;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;

class LoginController extends Controller
{
    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = RouteServiceProvider::HOME;

    /**
     * Override AuthenticatesUsers::login() to implement 2FA.
     *
     * @see AuthenticatesUsers::login() To the original login implementation.
     * @see https://github.com/Laragear/TwoFactor#logging-in To the Laragear\TwoFactor login implementation.
     *
     * @param Request $request
     *
     * @return JsonResponse|RedirectResponse|Response|SymfonyResponse
     */
    public function login(Request $request) {
        $credentials = $request->validate([
            $this->username() => 'required|string',
            'password' => 'required|string',
        ]);

        if (method_exists($this, 'hasTooManyLoginAttempts') &&
            $this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        $twoFactor = DB::table('two_factor_authentications')->where('label', $credentials['email'])->count();
        if ($twoFactor && ! $request->filled(config('app.2fa_field'))) {
            return response()->view(
                'two-factor::confirm',
                [
                    'credentials' => $credentials,
                    'remember' => $request->filled('remember'),
                ]
            );
        } else {
            if (Auth::attemptWhen($credentials, TwoFactor::hasCodeOrFails(), $request->filled('remember'))) {
                if ($request->hasSession()) {
                    $request->session()->put('auth.password_confirmed_at', time());
                }

                return $this->sendLoginResponse($request);
            }
        }

        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);
    }
}
```

It worked as expected, except that if users type a wrong 2FA code shw will be redirected back to login page (user/password). I can live with that, as it won't make explicit to an attacker if the wrong piece of data was the email, password or the TOTP code.

But at the end, is that right? Can it be improved somehow? Did I broke my auth toy?

PS: The documentation is far from clear when someone needs a custom login method like the case above (TOTP code in it's own form). But as I'm not sure if this is a bug with the middleware not attaching to POST login method, I will leave this as is for now.

## Reproduction
Not available yet.

## Expected behavior
It would be really nice if `Route::post()->middleware('2fa.confirm')` just worked as expected (i.e. force a user with 2FA enabled to enter TOTP code on it's own form page, leave users with 2FA disabled alone and just log them in). This would also leave such a critical method as `Auth\LoginController@login` alone.

## Stack Trace
The issue generates no stack trace.

**Comment by DarkGhostHunter** [comment]
I just deleted 15 paragraphs to just say this:

Yes, a bug.

You see, the middleware works over TOTP, which itself works over an authenticated user. If there is no authentication, it _should_ fail, even if the guest user will never be able to confirm, but that's the principle.

Fix incoming? Yes. When? The café opens tomorrow so I can sap wifi.

**Comment by denydias** [comment]
LOL! Been there, done that.

I thought I was crazy because your documentation is very clear on `middleware('2fa.confirm')` usage, including some examples with POST routes that should have worked just like I supposed they would. When it didn't and I was forced to override `Auth\LoginController@login`, then I feel something might be wrong.

No worries about when, Italo! My dirty fix works for now, so I have plenty of time to wait for your magic. If I only had a little bit more time on hands, I could even provide a PR for you... unfortunately this is not the case atm.

Thanks a lot for the quick response! Have a nice week and drink a good coffee while enjoying free wifi.

**Comment by DarkGhostHunter** [comment]
Seen the test, the test suite won't break, which means... I have to add a new test.

**Comment by DarkGhostHunter** [comment]
Now I remember it's the same functionality than the prior version. Which version where you on?

Also, it won't fix your login. If the middleware requires the user to be authenticated, you will get the message "two-factor required" forever because the credentials won't reach the login at all.

An alternative would be two to make catch the `InvalidCodeException` and return a response indicating the TOTP failed.

**Comment by DarkGhostHunter** [comment]
Since I can't fix this, let me recommend you to [this awesome `LoginRequest`](https://github.com/laravel/breeze/blob/47428e487061cd61f78eb5ca6ea12751d8ae08f2/stubs/default/App/Http/Requests/Auth/LoginRequest.php) courtesy of Laravel Breeze (is what I use for). You can just copy the file into your proyect.

Add the secret sauce as `attemptWhen()`:

```php
$attempt = Auth::attemptWhen(
    $this->only('email', 'password'),
    TwoFactor::hasCodeRoFails(),
    $this->boolean('remember')
);

if (! $attempt) {
    // ...
}
```

Then authenticate once it hits the controller.

```php
public function login(LoginRequest $request)
{
    try {
        $request->authenticate();
    } catch (InvalidCodeException $e) {
        return 'Two Factor code is required to proceed';
    }
}
```

**Comment by denydias** [comment]
My versions from composer:

```json
{
    "php": "^8.1",
    "laragear/two-factor": "^1.0",
    "laravel/framework": "^9.1"
}
```

Yeah, I was thinking about it and you're right. No cookies for me. If I understood it right, there's no way to implement the same behavior as the old [EnforceTwoFactorAuth](https://github.com/DarkGhostHunter/Laraguard/blob/v3.0.0/src/Listeners/EnforceTwoFactorAuth.php) unless I implement it myself. The requirement here is to have a way to check if an about to be logged in user (we know user email) has 2FA enabled so the TOTP entry form could be displayed.

PS: I was about to send the text above and your suggestion popped in. I will try it... Thanks again, @DarkGhostHunter!

**Comment by denydias** [comment]
Out of curiosity, why you removed that feature? Maybe the listener was too aggressive, but the feature it provides is pretty handy.

**Comment by DarkGhostHunter** [comment]
Because was a security risk. 

Credentials (password) are not to be saved somewhere. When you input your password, it saved it permanently in the view, meaning, anything could read the view and get your password. At that time, it was the only way to make the login hassle-free.

**Comment by denydias** [comment]
Sure. It is a security risk indeed.

But using encrypted connections mitigates that risk as the plain-text counterparts of users credentials will be available only to the UA and nowhere else in the loop. Of course there are MITM attacks that might obtain that data, but so is spoofing, phishing or even social engineering attacks capable to do so even if credentials are not presented to 2FA view. In the end it's all about compromises.

Maybe that functionality can return only if a secure protocol is in place, what's pretty usual these days.

Anyway, thanks for the reply and the suggestion of Breeze's LoginRequest. I'm working on it right now and looks promising.

Have a great week!

**Comment by DarkGhostHunter** [comment]
> Sure. It is a security risk indeed.
> 
> But using encrypted connections mitigates that risk as the plain-text counterparts of users credentials will be available only to the UA and nowhere else in the loop. Of course there are MITM attacks that might obtain that data, but so is spoofing, phishing or even social engineering attacks capable to do so even if credentials are not presented to 2FA view. In the end it's all about compromises.
> 
> Maybe that functionality can return only if a secure protocol is in place, what's pretty usual these days.
> 
> Anyway, thanks for the reply and the suggestion of Breeze's LoginRequest. I'm working on it right now and looks promising.
> 
> Have a great week!

I honestly don't think it's gonna come back as it was. I also tried flashing the credentials into the session, but that way there you can't add them to the incoming request... except using the middleware and flashing the session credentials into the request you have to capture after their are valid... 😴

**Comment by denydias** [comment]
It's comprehensible, Italo. I for one support your decision to remove that feature for good. If a developer (like me) wants that function back, it's up to him to implement it as well as facing the responsibility on doing so. As the maintainer of such a security sensitive module, you're 100% right on your reasoning to avoid security risks introduced by your code... plus loads of legal reasons to back you up. :wink:

**Comment by padre** [comment]
@denydias I also had to solve it in a similar way :-(
