### ISSUE TITLE
[1.x] Credentials aren't being flashed to session

### ISSUE THREAD

**Issue by aadrian624** [Laragear/TwoFactor#21]
### PHP & Platform

8.1.7 - Fedora 35 x64

### Laravel verion

9.17.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

When a user with 2FA enabled logs in and confirms their TOTP, they should be redirected to the application as authenticated.

### Description

The user is redirected back to the login page with an error stating that their credentials are invalid.  This seems to be caused by the session flash not being set.  Looking into `TwoFactorLoginHelper.php` I identified that `Illuminate\Contracts\Session\Session` does not have `flash()` as a member function [https://laravel.com/api/9.x/Illuminate/Contracts/Session/Session.html](https://laravel.com/api/9.x/Illuminate/Contracts/Session/Session.html)

```
protected function flashData(array $credentials, bool $remember): void
    {
        foreach ($credentials as $key => $value) {
            $credentials[$key] = Crypt::encryptString($value);
        }

        $this->session->flash($this->sessionKey, ['credentials' => $credentials, 'remember' => $remember]);
    }
```
As a result, when the TOTP form is submitted the credentials are blank.  And since validation is overridden due to `2fa_code` being present, the app kicks back a credentials not found error.
You may want to use `$this->session->put(...)` and `$this->session->forget(...)` in combination with `flashData()` and `getFlashedData()` to approximate `flash()` or instead use the `$request->session()` which does have `flash()`.

### Reproduction

```php
// https://github.com/Laragear/TwoFactor
```

### Are you a Patreon supporter?

No, don't give priority to this

**Comment by DarkGhostHunter** [comment]
You may be doing something wrong on your end, as [this test passes](https://github.com/Laragear/TwoFactor/blob/df7e8cb97ead1b3a4d7de52f17fb571753060122/tests/TwoFactorLoginHelperTest.php#L210-L223) while ensuring the `_2fa_login` session key exists and the subsequent login request is sucessful.

**Comment by aadrian624** [comment]
It's quite possible that I am. Though when I change `$this->session-flash(...)` to `$this->session->put(...)` the login flow works as expected. And running XDebug, I see that there are no credentials being retrieved when using flash.
![image](https://user-images.githubusercontent.com/16612937/179240199-6846a09b-734c-478e-a639-a827c4682b9d.png)
![image](https://user-images.githubusercontent.com/16612937/179240602-4542a4c0-c6c2-4791-b56d-802ecbe9ff5e.png)
![image](https://user-images.githubusercontent.com/16612937/179240123-dec68825-6165-4ca4-ac56-f8322d040eb0.png)
![image](https://user-images.githubusercontent.com/16612937/179239728-95435719-25bf-403e-ab7f-a3d19304d652.png)

**Comment by DarkGhostHunter** [comment]
This also happens when between the login failure and code post there is a new request:

1. Fail the attempt
2. Credentials are flashed
3. The 2FA Code View is rendered
4. _A new request happens_
5. _The new requests forgets the flashed credentials_
6. Issue a new 2FA Code.
7. Retrieve flashed Credentials, get an empty array.

**Comment by aadrian624** [comment]
Ok, that makes complete sense.  Looking at my login flow, only static assets are being loaded after the Blade view is rendered.  So I'm kind of at a loss here.  I've copied your code verbatim from the documentation and been though all of your classes and methods to try to make sense of what could be wrong.

**Comment by DarkGhostHunter** [comment]
Did you really tried a vanilla Laravel installation?

> [x] I can reproduce this bug in isolation (vanilla Laravel install)

**Comment by DarkGhostHunter** [comment]
I honestly cannot reproduce this issue. Please add a vanilla laravel installation that I can clone an fix this issue to reopen it.

**Comment by aadrian624** [comment]
I did try this with a vanilla Laravel install using Laravel UI and experienced the same issue...and looking at the L9 API doc, flash isn't a member function on the session contract.

I appreciate you looking into this issue!

**Comment by DarkGhostHunter** [comment]
> I did try this with a vanilla Laravel install using Laravel UI and experienced the same issue...and looking at the L9 API doc, flash isn't a member function on the session contract.
> 
> I appreciate you looking into this issue!

If it was the session contract, then you would get a `BadMethodCallException`, but instead you're getting empty credentials.

**Comment by aadrian624** [comment]
Well that's exactly what I would have thought...so that's where I'm confused about VS Code complaining about it being an unknown method and the API doc not mentioning flash on `Illuminate\Contracts\Session\Session`

**Comment by DarkGhostHunter** [comment]
> Well that's exactly what I would have thought...so that's where I'm confused about VS Code complaining about it being an unknown method and the API doc not mentioning flash on `Illuminate\Contracts\Session\Session`

Use PhpStorm EAP, the rest is like using notepad.

**Comment by DarkGhostHunter** [comment]
Closing this as being stale.
