### ISSUE TITLE
[1.1.2] Publishing provider files not working

### ISSUE THREAD

**Issue by shoXyRafael** [Laragear/TwoFactor#33]
### PHP & Platform

8.1 - Ubuntu

### Laravel version

9.3.4

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

I want to have all the files (views, configs) from the provider.

### Description

When I try to run the vendor publish command i am getting this info:

No publishable resources for tag [migrations].

And I even tried to add the provider to config/app.php

### Reproduction

```php
I normally installed the package like it says in the installation:
composer require laragear/two-factor

Then I am trying to publish the files with:
php artisan vendor:publish --provider="Laragear\TwoFactor\TwoFactorServiceProvider" --tag="migrations"
```

### Are you a Patreon supporter?

No, don't give priority to this

**Comment by DarkGhostHunter** [comment]
Something on your end. I just tested it.

```
$> php artisan vendor:publish --provider="Laragear\TwoFactor\TwoFactorServiceProvider" --tag="migrations"

Copied File [\vendor\laragear\two-factor\database\migrations\create_two_factor_authentications_table.php] To [\database\migrations\2022_08_21_182645_create_two_factor_au
thentications_table.php]
Publishing complete.
```

I can see the README is not clear about publishing the rest of the files. I updated that section.

> First, publish the migration, translations, views and config into your application, and use migrate to create the table that handles the Two-Factor Authentication information for each model you want to attach to 2FA.
>
> ```shell
> php artisan vendor:publish --provider="Laragear\TwoFactor\TwoFactorServiceProvider"
> php artisan migrate
> ```
