### ISSUE TITLE
Call Auth2FA::attempt gives warning 'Non static method 'attempt' should not be called statically.'

### ISSUE THREAD

**Issue by michelterstege81** [Laragear/TwoFactor#34]
### PHP & Platform

8.1.6 Windows

### Database

mysqlnd 8.1.6

### Laravel version

9.43.0

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

No warnings should be issued

### Description

When using this line:

$attempt = Auth2FA::attempt($request->only('email', 'password'), $request->filled('remember'));

like in the documentation VSCode intelephense marks it as: "Non static method 'attempt' should not be called statically."

### Reproduction

```php
/**
     * Handle an authentication attempt.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function authenticate(Request $request)
    {
        // If the user is trying for the first time, ensure both email and the password are
        // required to log in. If it's not, then he would issue its 2FA code. This ensures
        // the credentials are not required again when is just issuing his 2FA code alone.
        if ($request->isNotFilled('2fa_code')) {
            $request->validate([
                'email' => 'required|email',
                'password' => 'required|string'
            ]);
        }
        
        $attempt = Auth2FA::guard('admin')->attempt($request->only('email', 'password'), $request->filled('remember'));
    
        if ($attempt) {
            return redirect()->intended('/');
        }
 
        return back()->withErrors([
            'email' => 'The provided credentials do not match our records.',
        ])->onlyInput('email');
    }
```

**Comment by DarkGhostHunter** [comment]
That's clearly a bug on VS Code [intelephense](https://github.com/bmewburn/vscode-intelephense), because `guard('admin')` returns an intance of `TwoFactorLoginHelper` which has that dynamic method.

You can [raise this issue on their repository of 500+ issues](https://github.com/bmewburn/vscode-intelephense/issues) and pray it's fixed.

**Comment by michelterstege81** [comment]
If I do:

Auth2FA::guard('admin')->attempt

I get the warning on ::guard

When doing Auth2FA::attempt I get the warning on attempt.

The functions indeed return an instance from where the second call can be done using ->

but it's the first call using the static :: that gives the warning.

**Comment by michelterstege81** [comment]
I'm using:

use Laragear\TwoFactor\Facades\Auth2FA;

This is the actual warning:

![image](https://user-images.githubusercontent.com/118480982/207896777-d92bcfc4-6fdc-49ff-bb14-6f728cdc93b4.png)

**Comment by michelterstege81** [comment]
![image](https://user-images.githubusercontent.com/118480982/207897700-f28792f4-e8c3-41df-92dc-a747a692154a.png)

This is how it's done in Laravel's original Auth facade. In that case it has no warnings in VSCode.

If you change to:

/**
 * @method static bool attempt(array $credentials = [], mixed $remember = false)
 * @method static \Laragear\TwoFactor\TwoFactorLoginHelper view(string $view)
 * @method static \Laragear\TwoFactor\TwoFactorLoginHelper message(string $message)
 * @method static \Laragear\TwoFactor\TwoFactorLoginHelper input(string $input)
 * @method static \Laragear\TwoFactor\TwoFactorLoginHelper sessionKey(string $sessionKey)
 * @method static \Laragear\TwoFactor\TwoFactorLoginHelper guard(string $guard)
 *
 * @see \Laragear\TwoFactor\TwoFactorLoginHelper
 */
class Auth2FA extends Facade

the warning is gone

**Comment by DarkGhostHunter** [comment]
You're totally right. My mistake. Can you open a PR? I'm AFK right now.

**Comment by michelterstege81** [comment]
I created the PR. Hope I have done it right. It's the first time I use github. I normally use Bitbucket.

Meanwhile I have a small other question. Totally unrelated:

In the database table I see that a users email is used in the 'label' column and that is used as a label in the authenticator app. If every application does this, then it would be hard to distinguish in the authenticator app from which application it is. Would it be possible to get the APP_NAME in that column? Or at least send that to the auth app when pairing?

**Comment by DarkGhostHunter** [comment]
Published. Thanks for the PR.

> In the database table I see that a users email is used in the 'label' column and that is used as a label in the authenticator app. If every application does this, then it would be hard to distinguish in the authenticator app from which application it is. Would it be possible to get the APP_NAME in that column? Or at least send that to the auth app when pairing?

You mean [these lines](https://github.com/Laragear/TwoFactor/blob/a6900238bed7d345e0f0aa171b934fa4c58bab41/src/TwoFactorAuthentication.php#L100-L108)?

You can change it to your app name like this:

```php
/**
 * Returns the label for TOTP URI.
 *
 * @return string
 */
protected function twoFactorLabel(): string
{
    return config('app.name') . ' - '. $this->getAttribute('email');
}
```

I don't remember why I set the label to be the email, but I think now the format is `account:issuer`, like `john@mail.com:surrealdb.com`. I may change it on the next major version, since it's a breaking change.

**Comment by michelterstege81** [comment]
Thanks. I'll override the method.

Maybe it's an idea to make it a config option. Then it won't be a breaking change. Something like:

`/**
     * Returns the label for TOTP URI.
     *
     * @return string
     */
    protected function twoFactorLabel(): string
    {
        return config('two-factor.label', $this->getAttribute('email'));
    }`

See PR #36
