### ISSUE TITLE
Determine if user bypassed 2 factor with safe device.

### ISSUE THREAD

**Issue by stefan-sandberg** [Laragear/TwoFactor#38]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

Hi.

Thanks!
Great package, it has everything that Fortify lacks and is much more customizable.

One small feature Im missing is telling if the user is logged in with a real 2-factor authentication challenge or bypassed the auth with a "safe device". It would be optimal if the validate() method could set some session variable when bypassing the two-factor challenge. Or vice versa, some session variable being set only when the user did a real 2-factor auth.

I will have a middleware forcing users to confirm important actions if:
* They bypassed the 2 factor auth in the login
* Havent authenticated in xx time, since last time.

Maybe this feature exists but I've missed it somewhere?
Thanks.

### Code sample

```php
// If safe devices are enabled, and this is a safe device, bypass.
      if ($this->isSafeDevicesEnabled() && $user->isSafeDevice($this->request)) {
        
      **ADD**
        $this->request->session()->put("bypassed_two_factor", $time);
        
          return true;
      }
```

**Comment by DarkGhostHunter** [comment]
> telling if the user is logged in with a real 2-factor authentication challenge or bypassed the auth with a "safe device"

Note that not only works for authentication, but also protected routes or anything really. You can programmatically invoke a TOTP code.

Your feature request is quite fine. It should be `2fa_safe_device_bypassed_at`, and add a helper on the request/session that checks if the user bypassed a TOTP request using its safe device, and when it did it.

```php
session()->was2FABypassedBySafeDevice(); // bool
session()->bypassedBySafeDeviceAt(); // <Carbon>|null
```

Note that, with this solution, it will check if the 2FA was bypassed by a safe device during the session lifetime.

> Personally I'm inclined into using a `2fa` key and shove everything there. May be on the next major version.

**Comment by DarkGhostHunter** [comment]
> Maybe this feature exists but I've missed it somewhere?

After some going around, you say you need to confirm important actions using a middleware. 

> I will have a middleware forcing users to confirm important actions...

This can be done with the `2fa.confirm` middleware:

- When the user goes into the route, the middleware checks if it was recently confirmed.
- It redirects the user to a confirmation route
- The route runs the action and validates with the `totp` rule
- The rule checks if the code is a recovery code or TOTP code.
- The action sets that it was confirmed for a given time.
- The action redirects the user to where was intended.

The only caveat of the confirmation middleware is that it won't work for a default of 180 minutes. Instead, I may add a force flag to remove the recency check just before goes into the intended route, but is not on my current plans.
