### ISSUE TITLE
How to get the secret?

### ISSUE THREAD

**Issue by 1e4** [Laragear/TwoFactor#39]
How can I get the secret for use outside the Laravel application? I have a Node application the interfaces with this application. When passing in shared_secret to verify the 2fa code they gave it always returns false. So how can I derive the secret from the shared_secret?

For example [notp](https://github.com/guyht/notp) requires the secret key for the user

**Comment by DarkGhostHunter** [comment]
> How can I get the secret for use outside the Laravel application?

If you are wondering about the Shared Secret, you can easily get it from the user model relation itself. Pair that with a controller on a route and you can retrieve it.

```php
use App\Models\User;

Route::get('user/{user:id}/shared_secret', function (User $user) {
    return $user->twoFactorAuth->shared_secret;
});
```

> When passing in shared_secret to verify the 2fa code they gave it always returns false.

The Shared Secret is only given to the user once, at setup. After that, they need to confirm by generating a 2FA code on their device, which is returned to the app and checked against the code generated by the same server. If they're equal, it's true.

```php
Route::get('user/{user:id}/confirm_2fa', function (User $user) {
    return $user->confirmTwoFactorAuth(request('2fa_code')); // true|false
});
```

Most common problems for this to fail are wrong server time and/or device time.

> So how can I derive the secret from the shared_secret?

The shared_secret is **encrypted** on the database. Save yourself some lines and use the model itself from the first example to transmit it. It decrypts to a [Base32](https://en.wikipedia.org/wiki/Base32) uppercased string.

```php
Route::get('user/{user:id}/shared_secret', function (User $user) {
    return $user->twoFactorAuth->shared_secret;
});
```

**Comment by 1e4** [comment]
I understand how to get it in Laravel, but I'm using it outside of Laravel, I looked at the internals but couldn't figure out how to get it from the database

**Comment by DarkGhostHunter** [comment]
You can just query the database and decrypt the shared secret. You should receive a Base 32 in uppercase string.

If you don't have the ID of the row, you will need to query both model class name and model id:

```php
$secret = DB::table('two_factor_authentications')
    ->where([
        'authenticatable_type' => 'App/Models/User',
        'authenticatable_id' => 4
    ])
    ->first('shared_secret');

return Crypt::decrypt($secret);
```

**Comment by 1e4** [comment]
Thanks, solved it. Now to understand why the session isn't being flashed which seems related to #21
