### ISSUE TITLE
Migration should be optional

### ISSUE THREAD

**Issue by Grldk** [Laragear/TwoFactor#4]
### PHP & Platform

8.1.3

### Laravel verion

9.5.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

The migration included in this package should be optional. 

### Description

I'm migrating from the old Laraguard package. I already have a database table called `two_factor_authentications`, from a migration that has a slightly different name than the migration included with this package. 

This causes a `Table 'two_factor_authentications' already exists` error when running `php artisan migrate`, where the migration included in this package is called because it is not listed in my migrations table.

As far as I can see I cannot cancel this migration.

### Reproduction

```php
Schema::create('two_factor_authentications', function (Blueprint $table) {
            $table->bigIncrements('id');
});

then run php artisan migrate
```

### Are you a Patreon supporter?

No, don't give priority to this

**Comment by DarkGhostHunter** [comment]
The migration could check if the table already exists, but when using “down”, it would be destroyed. This should be _expected_, so it seems feasible.

I could make them optional by allow these to be publishable, but it would be a breaking change. I’ll put this on 2.x. Meanwhile, I'll add the check on the migration.

Italo Baeza C.

**Comment by DarkGhostHunter** [comment]
[Fixed](https://github.com/Laragear/TwoFactor/commit/efe103d6be0a9606c4b7ebc9e3dd8a9770b69997).

It will come into next patch version.
