### ISSUE TITLE
[1.x] Add Universal 2nd Factor (U2F)

### ISSUE THREAD

**Issue by dansleboby** [Laragear/TwoFactor#45]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

It will be nice to have an option to add U2F from hardware token like the Yubikey 5 NFC

![image](https://user-images.githubusercontent.com/4716382/226243761-ffb72e34-5b75-4d8f-82a4-9515ee72bab7.png)
![image](https://user-images.githubusercontent.com/4716382/226243767-94d2d814-4403-48a0-b8be-131a0dbebbc1.png)

### Code sample

```php
tbd
```

**Comment by DarkGhostHunter** [comment]
That's sounding great, but I don't have a Yubikey 5 NFC, and buying one from the store takes a whooping $100 I don't plan to invest in. Let alone a cheap testing phone (I only have one).

If anyone has both and is willing to add the code necessary to make it work, I'll accept that PR.

**Comment by dansleboby** [comment]
If you want to dig into i can give you a free key 🙃

**Comment by DarkGhostHunter** [comment]
> If you want to dig into i can give you a free key 🙃

Cool, that's half the problem fixed. I'll get a cheapo phone to test. Drop me an email if you want the address. I'm Chile, BTW.
