### ISSUE TITLE
Issue with migrating from darkghosthunter/laraguard 

### ISSUE THREAD

**Issue by es-roshanb** [Laragear/TwoFactor#46]
### PHP & Platform

8.1.17

### Database

Mysql 8.0.32

### Laravel version

10

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

It should be able to create `createTwoFactorAuth` for logged in user.
I see that the secret key are stored differently in two version. Did I miss any documentation to migrate properly?

### Description

So I updated laravel from 8 to 10, and also have migrated from
[darkghosthunter/laraguard](https://github.com/DarkGhostHunter/Laraguard) => [Laragear/TwoFactor](https://github.com/Laragear/TwoFactor).
So there is no any issue with doing new setup, but for the one which was setup from old version it gives payload issue. Please check the attachment.
![Screen Shot 2023-04-21 at 9 55 11 AM](https://user-images.githubusercontent.com/96721912/233539044-16bbafb4-bd31-4a7a-a9da-c7edec668cef.png)

### Reproduction

```php
$secret = $this->loggedInUser->createTwoFactorAuth();
```

**Comment by DarkGhostHunter** [comment]
That's a Crypt error. I can't see the full stack trace, so that's my guess, and shouldn't be a problem in the library.

**Comment by jonathan-bird** [comment]
This happens when you have existing items in two_factor_authentications when migrating. Removing the existing items gets it to work. I imagine a difference between the two libraries when migrating.
