### ISSUE TITLE
[1.x] How to use with Laravel Breeze

### ISSUE THREAD

**Issue by zenepay** [Laragear/TwoFactor#57]
### PHP & Platform

8.2 Ubuntu-20.04

### Database

MySql 8

### Laravel version

10

### Have you done this?

- [ ] I have checked my logs and I'm sure is a bug in this package.
- [ ] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

I try to modify App\Http\Requests\Auth\LoginRequest::authenticate()  by replacing Auth with Auth2FA, but it does not work.
I cannot use Auth::user() or Auth2FA::user() to get login user session.
How should I do?

### Description

 It prompts to ask 2FA form, but it does not work, no matter I enter correct 2fa code or not.

### Reproduction

```php
public function authenticate()
    {
        $this->ensureIsNotRateLimited();

        if (!Auth2FA::attempt($this->only('email', 'password'), $this->boolean('remember'))) { 
            RateLimiter::hit($this->throttleKey());

            throw ValidationException::withMessages([
                'email' => trans('auth.failed'),
            ]);
        }

        RateLimiter::clear($this->throttleKey());
    }
// what else I should do to make it work
```

**Comment by zenepay** [comment]
However, by using 2fa-confrim instead, it works well.
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified', '2fa.require', '2fa.confirm'])->name('dashboard');

// this method needs to set to all protected after login session. 
// I still prefer Auth2FA::attempt(), but it just does not work with me.

**Comment by DarkGhostHunter** [comment]
I would say to stick to middleware. It's far _easier_ to implement. I haven't touched Breeze in years to pick it up and fix it.

**Comment by zenepay** [comment]
Thank you, for now, I will go with that way.

**Comment by zenepay** [comment]
Please be updated that this is not a bug. I just found the solution. We just need to modify function rules in App\Http\Requests\Auth\LoginRequest::rules() as following:
```
    public function rules()
    {
        if(!empty($this->input('2fa_code'))){
            return [];
        }else{
            return [
                'email' => ['required', 'string', 'email'],
                'password' => ['required', 'string'],
            ];
        }
    }
    
   public function authenticate()
    {
        $this->ensureIsNotRateLimited();

        if (!Auth2FA::attempt($this->only('email', 'password'), $this->boolean('remember'))) { 
            RateLimiter::hit($this->throttleKey());

            throw ValidationException::withMessages([
                'email' => trans('auth.failed'),
            ]);
        }
        RateLimiter::clear($this->throttleKey());
    }
```
