### ISSUE TITLE
The MAC is invalid.

### ISSUE THREAD

**Issue by adibarly** [Laragear/TwoFactor#58]
### PHP & Platform

8.11 Mac M1

### Laravel version

10

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

![image](https://github.com/Laragear/TwoFactor/assets/26118753/13352a93-fad5-4a8f-b967-3e0eda426b9f)

### Description

![image](https://github.com/Laragear/TwoFactor/assets/26118753/fb2e257e-f3b2-4096-aea1-6f8968bd428b)

### Reproduction

```php
$authFA = Auth2FA::attempt($request->only('email', 'password'), $request->filled('remember'));
```

### Stack trace & logs

```shell
The MAC is invalid.
```

**Comment by DarkGhostHunter** [comment]
That doesn’t tell me much. I assume the MAC of your computer or server is invalid, as it may be used for creating the key. Italo Baeza C.El 14-09-2023, a la(s) 14:13, adibarly ***@***.***> escribió:﻿
PHP & Platform
8.11 Mac M1
Database
No response
Laravel version
10
Have you done this?

 I have checked my logs and I'm sure is a bug in this package.
 I can reproduce this bug in isolation (vanilla Laravel install)
 I can suggest a workaround as a Pull Request

Expectation

Description

Reproduction
$authFA = Auth2FA::attempt($request->only('email', 'password'), $request->filled('remember'));
Stack trace & logs
The MAC is invalid.

**Comment by DarkGhostHunter** [comment]
The error comes from Laravel itself. You'll have to post the issue there.
