### ISSUE TITLE
hasTwoFactorEnabled function not work because enabled_at still null 

### ISSUE THREAD

**Issue by elmarzouguidev** [Laragear/TwoFactor#61]
### PHP & Platform

8.1 ubuntu 22

### Database

mysql 8

### Laravel version

10.*

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

hasTwoFactorEnabled function not work because enabled_at still null 

### Description

hasTwoFactorEnabled function not work because enabled_at still null 

### Reproduction

```php
hasTwoFactorEnabled function not work because enabled_at still null
```

**Comment by DarkGhostHunter** [comment]
Use `$user->disableTwoFactorAuth()`.
