### ISSUE TITLE
[2.x] Clear Documentation Issues & UX Issues.

### ISSUE THREAD

**Issue by Fludem** [Laragear/TwoFactor#74]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

Hey,

This won't be an issue that's structured the way your forced issue templates are set. It's just a quick issue.

Documentation confused me for a good 5 minutes basically.

The repo is set as 2.x as the default branch. So I landed on that branch and this is what happened.

> I installed the package as instructed via composer.
> 
> Ran the command two-factor:install.
> 
> No command in that namespace was found.

I checked the package files in the Vendor namespace, and there was no command so it wasn't an autoload issue.

I checked packagist and then saw that 2.x is not yet stable. (It also said release on the right of the repository I'm just blind).

Also, when I went to switch branches, you had master listed as a branch, so I clicked that. It's stale but, it could confuse others but I jumped to the 1.x branch.

Now, I seem to be implementing your package smoothly after reading the correct documentation 😄 

I can submit a PR with a notice in the README where the installation instructions are informing the visitor to visit the other documentation as a fix? I think the correct solution is to use the 1.x branch as the default branch on this repository.

I assume you guys just aren't setting that as the default branch because some of Github's stuff and some tools always default to the default branch which makes things confusing if you guys are mainly spending time on version 2.x

### Code sample

```php
try {
} catch ($exception e) {
throw new Exception();
}
```

**Comment by DarkGhostHunter** [comment]
Laravel 11 is expected to launch next week, so I'll release 2.x as soon they pull the trigger. 

No worries, I had to make the 2.x default to correctly configure the CI/CD apps.

Also, all releases have their readme. If you navigate to the package in your protect, you will find the README.md for that version.

**Comment by Fludem** [comment]
Aye I found this, it was just the initial 'Huh?' 

All makes sense no problem have a nice week
