### ISSUE TITLE
Extending the section in documentation: set up->Logging in

### ISSUE THREAD

**Issue by OliverScrew** [Laragear/TwoFactor#9]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

I've installed the package following the readme.md. I still don't understand how to turn the login process into a two-step process for users who have enabled 2fa.  As I've read in the instructions I should add a field to the login form for the 2fa_code, and this works. Users without 2fa enabled are logged in without entering anything, and users who do have one must enter a code. 

However, I would prefer the user to first enter a valid username/password and then be asked for the 2fa_code. It would be great if the readme was a bit more explanatory on implementing the login routine. Alternatively, an example package that implements the functionality would be valuable. 

Thanks for your great work!

### Code sample

```php
- i have no idea on how to write that code.
```

### Are you a Patreon supporter?

No, don't give priority to this

**Comment by OliverScrew** [comment]
I finally got it, so no need to use time on it @DarkGhostHunter. I'll make a suggestion to the readme later today :)

**Comment by DarkGhostHunter** [comment]
> 2 days ago

**Comment by DarkGhostHunter** [comment]
You can thank me later:

https://github.com/Laragear/TwoFactor/tree/v1.1.0#logging-in
